In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings("ignore")
import io

import seaborn as sns


In [2]:
import missingno

In [3]:
Data=pd.read_csv("twitter_sentiment_data.csv")


In [4]:
Data.head()

sentiment                                            message  \
0         -1  @tiniebeany climate change is an interesting h...   
1          1  RT @NatGeoChannel: Watch #BeforeTheFlood right...   
2          1  Fabulous! Leonardo #DiCaprio's film on #climat...   
3          1  RT @Mick_Fanning: Just watched this amazing do...   
4          2  RT @cnalive: Pranita Biswasi, a Lutheran from ...   

              tweetid  
0  792927353886371840  
1  793124211518832641  
2  793124402388832256  
3  793124635873275904  
4  793125156185137153

In [5]:
Data.shape

(43943, 3)

In [6]:
Data.describe()

sentiment       tweetid
count  43943.000000  4.394300e+04
mean       0.853924  8.367966e+17
std        0.853543  8.568506e+16
min       -1.000000  5.926334e+17
25%        0.000000  7.970376e+17
50%        1.000000  8.402301e+17
75%        1.000000  9.020003e+17
max        2.000000  9.667024e+17

In [7]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43943 entries, 0 to 43942
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  43943 non-null  int64 
 1   message    43943 non-null  object
 2   tweetid    43943 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.0+ MB


In [8]:
Data.isna().sum()

sentiment    0
message      0
tweetid      0
dtype: int64

since there are no missing values will continue to clean the dataset 

In [9]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Joshua\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [10]:
corpus = []
for i in range(0, 43942):
    # Removing Hashtags
    review = re.sub(r'#', '', Data['message'][i])
    # Removing Chines
    review = re.sub(r'[^\x00-\x7F]+', '', Data['message'][i])
    # Removing Retweets
    review = re.sub(r'RT[\s]+', '', Data['message'][i])
    # Removing HyperLinks
    review = re.sub(r'https?:\/\/\s+', '', Data['message'][i])
    #selecting characters only
    review = re.sub('[^a-zA-Z]', ' ', Data['message'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)


In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 10000)
x = cv.fit_transform(corpus).toarray()
y = Data.iloc[0:43942, 0].values

In [12]:
#splitting the data into training and testing datset in the ratio 80:20
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

   MODEL GENERATION NAIVE BAYES

In [13]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB().fit(x_train,y_train)

In [14]:
y_pred=model.predict(x_test)
print(y_pred)

[1 0 1 ... 1 2 1]


In [15]:
from sklearn.metrics import confusion_matrix
confusion_m=confusion_matrix(y_test,y_pred)
print(confusion_m)

[[ 464  116  174   51]
 [ 129  670  549  167]
 [ 150  437 3458  585]
 [  27   40  291 1481]]


In [16]:
from sklearn import metrics
score=metrics.accuracy_score(y_pred,y_test)
print("accuracy using naive bayes algo is "+str(score))


accuracy using naive bayes algo is 0.6909773580612129


In [17]:
accuracy=score*100
print("accuracy is "+str(accuracy))

accuracy is 69.09773580612128


In [18]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB(alpha=5).fit(x_train,y_train)

In [19]:
predictions = model.predict(x_test)
print(predictions)

[1 1 1 ... 1 1 1]


In [20]:
from sklearn import metrics
accuracy_score = metrics.accuracy_score(predictions,y_test)
print(f'Accuracy score = {accuracy_score*100}')

Accuracy score = 67.95994993742178


In [21]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB(alpha=20).fit(x_train,y_train)
predictions = model.predict(x_test)
print(predictions)
accuracy_score = metrics.accuracy_score(predictions,y_test)
print(f'Accuracy score = {accuracy_score*100}')

[1 1 1 ... 1 1 1]
Accuracy score = 58.379792922971895


In [22]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB(alpha=50).fit(x_train,y_train)
predictions = model.predict(x_test)
print(predictions)
accuracy_score = metrics.accuracy_score(predictions,y_test)
print(f'Accuracy score = {accuracy_score*100}')

[1 1 1 ... 1 1 1]
Accuracy score = 53.41904653544203


In [23]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB(alpha=100).fit(x_train,y_train)
predictions = model.predict(x_test)
print(predictions)
accuracy_score = metrics.accuracy_score(predictions,y_test)
print(f'Accuracy score = {accuracy_score*100}')

[1 1 1 ... 1 1 1]
Accuracy score = 52.759130731596315


In [24]:
from sklearn.naive_bayes import BernoulliNB
BNB=BernoulliNB()
BNB.fit(x_train,y_train)
accuracy_score_bnb=metrics.accuracy_score(BNB.predict(x_test),y_test)
print(accuracy_score_bnb*100)

67.447946296507


In [25]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
token = RegexpTokenizer(r'[A-Za-z0-9]+')

cv=CountVectorizer(stop_words='english',ngram_range=(2,2), tokenizer=token.tokenize)
text_counts = cv.fit_transform(Data['message'])

x_train, x_test, y_train, y_test = train_test_split(text_counts, Data['sentiment'], test_size = 0.25, random_state = 5)

MNB=MultinomialNB()                                                                      
MNB.fit(x_train,y_train)                                                                         

accuracy_score=metrics.accuracy_score(MNB.predict(x_test),y_test)
print(f'Accuracy score = {accuracy_score*100}')

Accuracy score = 65.18296013107592


In [26]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer
token = RegexpTokenizer(r'[A-Za-z0-9]+')

cv=CountVectorizer(stop_words='english',ngram_range=(2,2), tokenizer=token.tokenize)
text_counts = cv.fit_transform(Data['message'])

x_train, x_test, y_train, y_test = train_test_split(text_counts, Data['sentiment'], test_size = 0.25, random_state = 5)

MNB=MultinomialNB(alpha=5)                                                                      
MNB.fit(x_train,y_train)                                                                         

accuracy_score=metrics.accuracy_score(MNB.predict(x_test),y_test)
print(f'Accuracy score = {accuracy_score*100}')

Accuracy score = 62.4795193883124


In [27]:
cv=CountVectorizer(stop_words='english',ngram_range=(3,3), tokenizer=token.tokenize)
text_counts = cv.fit_transform(Data['message'])

x_train, x_test, y_train, y_test = train_test_split(text_counts, Data['sentiment'], test_size = 0.25, random_state = 5)

MNB=MultinomialNB()                                                                      
MNB.fit(x_train,y_train)                                                                         

accuracy_score=metrics.accuracy_score(MNB.predict(x_test),y_test)
print(f'Accuracy score = {accuracy_score*100}')

Accuracy score = 57.09084289095212


In [28]:
cv=CountVectorizer(stop_words='english',ngram_range=(3,3), tokenizer=token.tokenize)
text_counts = cv.fit_transform(Data['message'])

x_train, x_test, y_train, y_test = train_test_split(text_counts, Data['sentiment'], test_size = 0.25, random_state = 5)

MNB=MultinomialNB(alpha=5)                                                                      
MNB.fit(x_train,y_train)                                                                         

accuracy_score=metrics.accuracy_score(MNB.predict(x_test),y_test)
print(f'Accuracy score = {accuracy_score*100}')

Accuracy score = 62.9528490806481


In [29]:
cv=CountVectorizer(stop_words='english',ngram_range=(3,3), tokenizer=token.tokenize)
text_counts = cv.fit_transform(Data['message'])

x_train, x_test, y_train, y_test = train_test_split(text_counts, Data['sentiment'], test_size = 0.25, random_state = 5)

MNB=MultinomialNB(alpha=20)                                                                      
MNB.fit(x_train,y_train)                                                                         

accuracy_score=metrics.accuracy_score(MNB.predict(x_test),y_test)
print(f'Accuracy score = {accuracy_score*100}')

Accuracy score = 58.32878208629164


FINAL MODEL 

In [30]:
cv=CountVectorizer(stop_words='english',ngram_range=(1,1), tokenizer=token.tokenize)
text_counts = cv.fit_transform(Data['message'])

x_train, x_test, y_train, y_test = train_test_split(text_counts, Data['sentiment'], test_size = 0.25, random_state = 2)

from sklearn.naive_bayes import ComplementNB

CNB = ComplementNB()                                             
CNB.fit(x_train,y_train)

accuracy_score=metrics.accuracy_score(CNB.predict(x_test), y_test)

accuracy_score=metrics.accuracy_score(CNB.predict(x_test),y_test)
print(f'Accuracy score = {accuracy_score*100}')

Accuracy score = 70.4806116876024
